version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dhanlaxmi-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dhanlaxmi-saree-sadan
    volumes:
      - mongodb_data:/data/db
    networks:
      - dhanlaxmi-network

volumes:
  mongodb_data:

networks:
  dhanlaxmi-network:
    driver: bridge